title 0_4 new note

browser->server: HTTP POST https://studies.cs.helsinki.fi/exampleapp/new_note

note over server:
notes is beeing updated with the new content
end note

server-->browser: HTTP 302 https://studies.cs.helsinki.fi/exampleapp/notes

note over browser:
a redirect was initiated
end note

browser->server: HTTP GET https://studies.cs.helsinki.fi/exampleapp/notes
server-->browser: HTML-code
browser->server: HTTP GET https://studies.cs.helsinki.fi/exampleapp/main.css
server-->browser: main.css
browser->server: HTTP GET https://studies.cs.helsinki.fi/exampleapp/main.js
server-->browser: main.js

note over browser:
browser starts executing js-code
that requests JSON data from server 
end note

browser->server: HTTP GET https://studies.cs.helsinki.fi/exampleapp/data.json
server-->browser: [{ content: "notelinote" }, ...]

note over browser:
browser executes the event handler
that renders notes to display
end note 